// PROJECTS' INFO KEPT HERE

export const homeObjOne = {
  id: "project-1",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "01.",
  headline: "MoonBase. Projects Dashboard",
  description:
    "Built using React.js and Semantic UI on the frontend and Firebase for databasing, authentication, storage, and hosting. I constantly find myself with a list of ongoing projects to work on or issues to resolve while in development - this app helps to stay on track.",
  technologies: "JavaScript, React.js, Firebase",
  buttonLabel: "View Project",
  buttonLabel2: "View Source Code",
  imgStart: true,
  img: "../../images/Moonbase_2.png",
  alt: "Project 1",
  primary: false,
  dark: true,
  darkText: true,
  codeUrl: "https://github.com/robdcampbell/Project-Tracker-Moonbase",
  projectUrl: "https://projectdashboard-production.web.app/login",
};

export const homeObjTwo = {
  id: "project-2",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "02.",
  headline: "HomeRoom",
  description:
    "A resource to make preparing for your financial future simple and easy to visualize. ( Currently in progress. )",
  technologies: "JavaScript, React.js, Firebase, D3.js",
  buttonLabel: "View Project",
  buttonLabel2: "View Source Code",
  imgStart: false,
  img: "../../images/homeroom-home.png",
  alt: "Project 2",
  primary: true,
  dark: true,
  darkText: false,
  codeUrl: "https://github.com/robdcampbell/HomeRoom",
  projectUrl: "https://rc-homeroom.netlify.app/",
};

export const homeObjThree = {
  id: "project-3",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "03.",
  headline: "robcampbelldev.com (this website) ",
  description: "My digital portofolio to see what I've been tinkering at.",
  technologies: "JavaScript, React.js, React Styled Components",
  buttonLabel2: "View Source Code",
  imgStart: false,
  img: "../../images/portfolio_dark.png",
  alt: "Project 3",
  primary: true,
  dark: true,
  darkText: false,
  codeUrl: "https://github.com/robdcampbell/reactPortfolio",
  // projectUrl: "https://react-movielibrary-rdc.netlify.app/",
};

export const homeObjFour = {
  id: "project-4",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "04.",
  headline: "Authentication Boilerplate",
  description:
    "Using React.js and React-Bootstrap, this starter project can be reconfigured with a new Firebase project simply by updating the Firebase SDK configuration info in a private environmental variable file",
  technologies: "JavaScript, React.js, Firebase, Bootstrap",
  buttonLabel: "View Project",
  buttonLabel2: "View Source Code",
  imgStart: true,
  img: "../../images/authBoilerPlate_ORANGE.png",
  alt: "Project 4",
  primary: false,
  dark: true,
  darkText: true,
  codeUrl: "https://github.com/robdcampbell/firebaseAuthStarter",
  projectUrl: "https://rc-auth-development.web.app/",
};

export const homeObjFive = {
  id: "project-5",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "05.",
  headline: "Movie Library (React.js)",
  description:
    "Fetching movie data from the OMDb API, this React.js Movie Library displays movies based on your search criteria.",
  technologies: "JavaScript, React.js",
  buttonLabel: "View Project",
  buttonLabel2: "View Source Code",
  imgStart: false,
  img: "../../images/movieLibraryPic.png",
  alt: "Project 5",
  primary: true,
  dark: true,
  darkText: false,
  codeUrl: "https://github.com/robdcampbell/movieLibrary",
  projectUrl: "https://react-movielibrary-rdc.netlify.app/",
};

// NOT DONE
export const homeObjSix = {
  id: "project-6",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "06. ",
  headline: "NASA Explorer (in progress...)",
  description:
    "Using external data accessible through NASA's public API's, this app is used to exhibit daily information provided from NASA.",
  buttonLabel: "View Project",
  buttonLabel2: "View Source Code",
  imgStart: true,
  img: "../../images/svg-5.svg",
  alt: "Project 6",
  primary: false,
  dark: true,
  darkText: true,
  codeUrl: "https://github.com/robdcampbell/nasaDaily",
  projectUrl: "",
};
